### ISSUE TITLE
voteraw api?

### ISSUE THREAD

**Issue by coolaj86** [dashpay/insight-api#21]
Are there Dash-specific APIs? Like `voteraw`, `masternode`, etc?

I don't see documentation for those sorts of things.

**Comment by quangogster** [comment]
https://dashpay.atlassian.net/wiki/spaces/DOC/pages/131924073/RPC+commands

**Comment by nmarley** [comment]
Hi, some of this functionality is added, but I don't think every JSONRPC command has been implemented in Insight-API. Since Insight is intended to be a block explorer web app and intended to be open to the public, only read-only commands are implemented and I don't think it makes sense to implement any of the vote commands in Insight.

You can see the routes available starting here in `lib/index.js`: https://github.com/dashevo/insight-api/blob/fc794706ecf329beac7d4218486f45bdd2974eb9/lib/index.js#L174

**Comment by jhodges10** [comment]
@nmarley I know it's an edge case, but we're thinking about using `voteraw` over the web for Dash Nexus, potentially through the Insight API and if this was in the Core-managed Insight API it would help us with security through obfuscation, by separating our infrastructure into separately managed parts.

Otherwise, we'll fork the Insight API and run on our version that has this additional method, but I'd prefer to use the Core-managed Insight API for the aforementioned reasons. (With the intention of embracing the DAPI when it becomes available)
